### PR TITLE
Fix Transaction Types

### PR DESCRIPTION
**Pull request by avkos**

### CODE REVIEW

**Review by danforbes — COMMENTED** [review]
It seems like there are a lot of formatting-only changes in this PR. Why were those changes made? Would it be possible to revert those so that it's easier to understand the relevant changes to the code? Alternatively, could you provide some additional information in the PR description to help understand what relevant changes were made?

**Review by danforbes — COMMENTED** [review]
Is this PR meant to address #37? The [`ZKsyncWallet.deposit`](https://github.com/ChainSafe/web3-plugin-zksync/blob/71f8224082f024c577d91b00f03a0a2f7a932d4d/src/zksync-wallet.ts#L161-L176) method is still using an ad hoc type (as are the other wallet transactions)...

**Review by luu-alex — APPROVED** [review]

**Comment by luu-alex** [comment]
other than what dan said, i think there were other changes made like 
```
getAddress(): Promise<Address>;
	getAddress(): Address;
```
if u can list out the changes that would be great, but if the scope of this was to fix transaction types it looks like you've changed it :)

**Review by Muhammad-Altabba — APPROVED** [review]

**Review by danforbes — COMMENTED** [review]
I still see the use of lots of ad hoc transaction parameters in `adapters.ts`, for instance, `deposit`, `estimateGasDeposit`, `getFullRequiredDepositFee`, `requestExecute`, `estimateGasRequestExecute`, `getRequestExecuteAllowanceParams`, `getRequestExecuteContractMethod`, `getRequestExecuteTx` and `withdraw`. Would it be possible to create one or more transaction types that are exposed to developers and can be used as parameters for these methods?

**Review by danforbes — APPROVED** [review]

**Pull request merged**
